### ISSUE TITLE
Can't click off "this is your first notification" alert

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#102]
Steps to reproduce:

1. Visit `/new-topic` route as a logged out user
2. Log in as an unregistered user
3. Sign up
4. Type new `/new-topic` route into url bar
5. Scream

From testing, looks like this only happens under these exact conditions - if a user doesn't do step 4 (and it's unlikely they will) then this won't happen, and it can be fixed by refreshing.

I'd say this is a bit of an edge case, so low priority.

**Comment by viorelaioia** [comment]
I am also able to reproduce this issue when creating new account.
**Steps to reproduce:**
1. Login to discourse with a new email (that doesn't have a discourse account associated)
2. Click Create New Account button -> First notification banner is displayed
3. Click the notification -> The notification dissapears
4. Click another element on the page 

**Expected:**
The notification is not shown anymore.

**Actual:**
The notification is shown again. After each click on the page, the notification is displayed. 
Refreshing the page will make it dissapear.

See [video](https://vimeo.com/232971248)

**Comment by LeoMcA** [comment]
Fixed with: https://github.com/mozilla/discourse-mozilla-theme/commit/4073b852284fc842a91becbbe4521b0e2a9863ad

**Comment by lemonforest** [comment]
This issue seems to have cropped up again. The social account used was GitHub on Kicad forums.  It looks like their current version is almost a year old and, I'm going out on a limb here~, the likely solution/suggestion would be to update to the latest stable but figured I'd mention it since this was marked resolved almost 2 years ago.

Thanks!

<meta name="generator" content="Discourse 2.2.0.beta2 - https://github.com/discourse/discourse version 34e8d17ad041dd3e4d02dc5a28b5f510cd8cca5f">

**Comment by LeoMcA** [comment]
Hi @lemonforest, this was an issue with a custom theme we were running on our own Discourse instance. I would suggest contacting the owners of that forum to let them know of the problem.
