### ISSUE TITLE
macOS 10.14/iOS 12.0 Safari login error

### ISSUE THREAD

**Issue by rleitan** [mozilla/discourse#156]
[Environment]:
iOS 12.0 
Browser: Safari, Firefox, Chrome

[Steps to reproduce]:
1.Open an iOS browser (e.g. Firefox)
2.Navigate to https://discourse.mozilla.org
3.Tap Log in button 
4.Enter valid credentials (account with LDAP)

[Expected results]:
Successful log in

[Actual results]:
Log in error
![thumbnail](https://user-images.githubusercontent.com/41474886/45225578-8eddc480-b2c5-11e8-823d-67264bb15b79.jpg)

**Comment by rleitan** [comment]
https://sso.mozilla.com/ and https://meta.discourse.org are not affected

**Comment by LeoMcA** [comment]
Looks like this is an issue with Safai on macOS too: https://discourse.mozilla.org/t/access-to-forum-fails-with-safari/32695

Still haven't got round to finding a mac to debug it on, but once I'm back at uni I should be surrounded by them

**Comment by LeoMcA** [comment]
Attempted to reproduce on macOS 10.14.1 and Safari 12.0.1, but couldn't. It could be that Apple have fixed an issue causing this.

Would still like to nail down what was happening though - it's curious that it was affecting Mozilla Discourse but not Meta Discourse nor sso.mozilla.org (ruling out a general Discourse issue, or a general IAM issue). But since it doesn't seem to happen on the latest version, this is much less of a priority.

**Comment by LeoMcA** [comment]
After attempting again, I could reproduce the bug with passwordless login.

I've requested a loaner mac to properly debug this issue.

**Comment by LeoMcA** [comment]
Okay, thanks to the loaner mac I've got more understanding with what's going wrong:

1. User goes to Discourse, clicks log in
2. A session cookie is set on the client containing the `state` value which is also sent to auth0
3. User logs in on auth0
4. Auth0 redirects user to Discourse, but no session cookie is set
5. Discourse attempts to compare the null `state` value with the one returned by auth0 and throws a csrf error

This is consistently repeatable when logging in with LDAP. With Passwordless this only seems to happen when copying and pasting the login url to the same tab as the login was initiated in, if the link is clicked an opened normally then the error doesn't happen.

Seems to always work with GitHub.

**Comment by LeoMcA** [comment]
*Finally* worked out what's going on here:

Discourse is setting the [`SameSite`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_cookies) cookie option to `Lax`.

When I get Discourse to not set that option at all, the issue goes away.

Not sure not setting that option is a solution, as it has security implications, I'll ask infosec. I think the bug here resides somewhere within Auth0 or Safari.

Some theories as to why this might be happening in Auth0/Safari:

* The final auth.mozilla.auth0.com request before redirecting to Discourse when logging in with GitHub (which works with `samesite=lax`) is a `GET`, whereas the final request with LDAP is a `POST`

**Comment by LeoMcA** [comment]
It's a Safari bug: https://bugs.webkit.org/show_bug.cgi?id=188165

Which has been fixed with the latest technology preview: https://webkit.org/blog/8658/release-notes-for-safari-technology-preview-77/

I've verified I can log in with LDAP when using the preview.

**Comment by LeoMcA** [comment]
Looks like other people have noticed it upstream: https://meta.discourse.org/t/infinite-sso-redirect-on-safari/110857

I've [posted asking for their opinion of removing the `samesite` cookie option](https://meta.discourse.org/t/infinite-sso-redirect-on-safari/110857/6?u=leomca).

**Comment by hmitsch** [comment]
Awesome analysis, @LeoMcA. Thanks a lot!!

**Comment by LeoMcA** [comment]
Closing as wontfix, the Safari fix should make its way through to release soon enough.
