### ISSUE TITLE
Non-infinite scroll

### ISSUE THREAD

**Issue by nukeador** [mozilla/discourse#212]
I can't scroll down to topics previous to May 28 here when logged in

https://discourse.mozilla.org/c/voice

It seems this doesn't happen when log-out.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/DISC-22)

**Comment by TannerFilip** [comment]
It appears to be happening when it reaches a post in a private subcategory. On my test account, once the group to see that private subcategory was applied, I could no longer see past May 28th. After I removed it, I could scroll infinitely.

**Comment by TannerFilip** [comment]
This is what I've figured out so far:

1. Commenting out [part of the common.scss file](https://github.com/mozilla/discourse-mozilla-theme/blob/3c763016e53b7d99ca8feae3a013985d7ee3727d/common/common.scss#L79) that deals with Common Voice resolves this. That obviously means all posts are going to show up, though. 

2. As of right now, the last two posts on [page 3 (zero-indexed)](https://discourse.mozilla.org/c/voice.json?page=2) are hidden by the css mentioned there.

3. As of right now, the first post on page 4 is a private category, which is also hidden by that css since it's not in the "Common Voice" category. I think this is where the problem is. I'm guessing that the event to trigger another page to load is in there somewhere, and since it's not being rendered, the new page doesn't load.

Replacing `display: none;` with `visibility: collapse;` mostly resolves this. It does introduce a problem where the bottom of the page is just a big white space, but that's more of an aesthetic thing.

**Comment by LeoMcA** [comment]
Thanks for figuring this out @TannerFilip.

The big white space is a bit annoying, but only appears on the CV category, so worth it to get infinite scroll working. Not sure if we can fix that with CSS.

We should probably just do this properly on the server side: https://github.com/mozilla/discourse/issues/213
