### ISSUE TITLE
Download Firefox banner

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#74]
Inspired by Google: https://twitter.com/cwiiis/status/867302736265719809

_As a Chrome user visiting the NDA category, I should see a banner encouraging me to download Nightly._

**Comment by jvillalobos** [comment]
I don't think that will be very effective in that context. If developers are asking questions about Firefox add-on development, then they use Firefox at least part time. Pushing them to download it just because they happened to post on Discourse using Chrome or another browser would be annoying, IMO.

Is there a reason this is targeted only for the add-ons category?

**Comment by LeoMcA** [comment]
> If developers are asking questions about Firefox add-on development, then they use Firefox at least part time.

Ah, now that would explain the high numbers of non-Firefox users I was seeing in the analytics.

> Is there a reason this is targeted only for the add-ons category?

I was thinking it would give us the biggest test-bed to see how effective it was. Now I'm thinking we want to try this with smaller more internal categories, and then scale up to larger more public-facing categories.

Thanks for the feedback!

**Comment by LeoMcA** [comment]
> As a Chrome user visiting the NDA category, I should see a banner encouraging me to download Nightly.

This has been deployed to prod: https://github.com/mozilla/discourse-mozilla-theme/commit/7921ea3f71ca131300dce15ed65b2b2a1617c634

Will open another issue to look at the analytics from this and expand to more categories/browsers.
