### ISSUE TITLE
Update link colour in posts

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#94]
While waiting for #82 to be unblocked upstream, at least make the link colour in posts bluer as a stop-gap solution.

**Comment by LeoMcA** [comment]
@m-branson I'm not sure any of options from the [color palette](https://mozilla.ninja/visualelements) make a particularly good link color:

**Blue 2 `#558194`**: currently in use, too dark

![screenshot from 2017-08-30 17-52-15](https://user-images.githubusercontent.com/755354/29884649-01b0c5b0-8dac-11e7-8f78-ed282dc138cc.png)

**Blue 3 `#88d1f1`**: I would say too light

![screenshot from 2017-08-30 17-53-23](https://user-images.githubusercontent.com/755354/29884705-279b448a-8dac-11e7-8ee7-6accc3127727.png)

**Neon Blue 1 `#3dfefd`**: makes my eyes hurt

![screenshot from 2017-08-30 17-54-30](https://user-images.githubusercontent.com/755354/29884749-527cc76e-8dac-11e7-8322-3bb41748aada.png)

**Neon Blue 2 `#229d9a`**: not sure I'm a fan of turquoise links

![screenshot from 2017-08-30 17-55-17](https://user-images.githubusercontent.com/755354/29884780-6e66ac88-8dac-11e7-878e-01306ea17851.png)

**Blue 2⅓ `#669CB3`**: a blend of Blue 2/Blue 3, possibly the best, but still not brilliant

![screenshot from 2017-08-30 17-56-50](https://user-images.githubusercontent.com/755354/29884955-ec704c1a-8dac-11e7-900a-72e4fec2986d.png)

Being pastel colours, I think they all lack the intensity that people expect from a link. Then again, I'm a little bit colour-blind, so another set of eyes on this would be helpful. 👁 👁

**Comment by m-branson** [comment]
Hey @LeoMcA, completely agree with you that these colors aren't the best for this use case. I feel that we may be forcing a color link option here. 

What if we move away from the color idea for a moment and simply give links `text-decoration-line: underline`? This could solve the issue of competing colors (due to the plethora of category colors Discourse inherently has) while also solving for accessibility (those users who are color-blind need not rely on color to identify links).

Additionally, UI across the site could become black, white or shades of gray. e.g. the user notification counter could be a black circle with a white number. You're nearly doing this across the site as it is, why not push it further and make a rule? This fully allows category colors to exist without competing or being disruptive.

Looking forward to your thoughts!

**Comment by LeoMcA** [comment]
I like it!

This issue is about a quick-fix for links in posts, so I'll apply an underline to them and leave it at that for this sprint.

Tracking wider UI changes in #82
