### ISSUE TITLE
Create process for post-sprint future

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/discourse#98]
Once I start at Uni it makes more sense to work in Kanban mode, rather than in sprints.

- [x] move to JIT release notes
  - [x] move feature requests to [a tag](https://discourse.mozilla.org/tags/c/meta/feature-request)
  - [x] split up help subcategory to support and faq
  - [x] move announcements to [a restricted tag](https://discourse.mozilla.org/tags/announcement)
  - [x] discourse release notes stay in parsys but are tagged with `release` (and `announcement` for releases we really want to shout about) so people can follow along without subscribing to participation systems generally
- [x] review overview board, make changes if any necessary

  > let's aim not to have "column collapsing" by using :arrow_down_small: in one column
- [x] prioritize backlog

**Comment by hmitsch** [comment]
May I suggest to say "work in Kanban mode", instead of "with a prioritized backlog". 

The main differences and similarities are:
Both Scrum and Kanban require a prioritized backlog.

In Scrum we use time boxes to pull a number of items from the product backlog into the sprint backlog and then aim to deliver these scope items during the sprint.
In Kanban we pull from the product backlog each time we are ready to take the next item on board. 

As you will be entering a period of less deterministic availability a flow-optimization approach such as Kanban will be more helpful than the batched approach Scrum currently provides us.
